(defun my-prog-mode-hook ()
  (unless (equal major-mode 'org-mode)
    (fci-mode 1)))
(add-hook 'prog-mode-hook 'my-prog-mode-hook)
(add-to-list 'load-path "~/.emacs.d/init/progs/")
(require 'my-haskell)
(require 'my-python)
(require 'my-org)
(provide 'progs)
